# autogenerated by docgen
# source: /home/runner/work/nim-lang/nim-lang/lib/js/asyncjs.nim
# rdoccmd: -r:off
import "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/asyncjs_examples_1.nim"
import "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim"
