#[
autogenerated by docgen
loc: /home/runner/work/nim-lang/nim-lang/lib/js/dom.nim(37, 17)
rdoccmd: -b:js -r:off
]#
import std/assertions
import "/home/runner/work/nim-lang/nim-lang/lib/js/dom.nim"
{.line: ("/home/runner/work/nim-lang/nim-lang/lib/js/dom.nim", 37, 17).}:
  proc example() = window.location.reload()
  discard setTimeout(example, 5_000)

