#[
autogenerated by docgen
loc: /home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim(69, 3)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim", 69, 3).}:
  doAssert toNumber(big"2147483647") == 2147483647.int

