#[
autogenerated by docgen
loc: /home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim(81, 3)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim", 81, 3).}:
  doAssert (big"42" * big"9") == big"378"

