#[
autogenerated by docgen
loc: /home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim(14, 3)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim", 14, 3).}:
  doAssert big(1234567890) == big"1234567890"
  doAssert 0b1111100111.big == 0o1747.big and 0o1747.big == 999.big

