#[
autogenerated by docgen
loc: /home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim(194, 3)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim", 194, 3).}:
  var big1: JsBigInt = big"11"
  big1 /= big"2"
  doAssert big1 == big"5"

