#[
autogenerated by docgen
loc: /home/runner/work/nim-lang/nim-lang/lib/js/jsconsole.nim(21, 17)
rdoccmd: -r:off
]#
import std/assertions
import "/home/runner/work/nim-lang/nim-lang/lib/js/jsconsole.nim"
{.line: ("/home/runner/work/nim-lang/nim-lang/lib/js/jsconsole.nim", 21, 17).}:
  console.log "%c My Debug Message", "color: red" # Notice the "%c"
  console.log "%c My Debug %c Message", "color: red", "font-size: 2em"

