#[
autogenerated by docgen
loc: /home/runner/work/nim-lang/nim-lang/lib/js/jscore.nim(138, 5)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/nim-lang/nim-lang/lib/js/jscore.nim"
{.line: ("/home/runner/work/nim-lang/nim-lang/lib/js/jscore.nim", 138, 5).}:
  var arrai = @[1, 2, 3]
  assert arrai.shift() == 1
  assert arrai == @[2, 3]

