#[
autogenerated by docgen
loc: /home/runner/work/nim-lang/nim-lang/lib/js/jscore.nim(146, 21)
rdoccmd: -r:off
]#
import std/assertions
import "/home/runner/work/nim-lang/nim-lang/lib/js/jscore.nim"
{.line: ("/home/runner/work/nim-lang/nim-lang/lib/js/jscore.nim", 146, 21).}:
  queueMicrotask(proc() = echo "Microtask")

