# autogenerated by docgen
# source: /home/runner/work/nim-lang/nim-lang/lib/js/jsconsole.nim
# rdoccmd: -r:off
import "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsconsole_examples_1.nim"
