# autogenerated by docgen
# source: /home/runner/work/nim-lang/nim-lang/lib/js/jscore.nim
# rdoccmd: -r:off
import "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jscore_examples_3.nim"
