/* Generated by the Nim Compiler v1.9.3 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;

function toJSStr(s_33556855) {
  var result_33556856 = null;

    var res_33556894 = newSeq_33556873((s_33556855).length);
    var i_33556895 = 0;
    var j_33556896 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556895 < (s_33556855).length)) break Label2;
          var c_33556897 = s_33556855[i_33556895];
          if ((c_33556897 < 128)) {
          res_33556894[j_33556896] = String.fromCharCode(c_33556897);
          i_33556895 += 1;
          }
          else {
            var helper_33556910 = newSeq_33556873(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556911 = c_33556897.toString(16);
                  if ((((code_33556911) == null ? 0 : (code_33556911).length) == 1)) {
                  helper_33556910.push("%0");;
                  }
                  else {
                  helper_33556910.push("%");;
                  }
                  
                  helper_33556910.push(code_33556911);;
                  i_33556895 += 1;
                  if ((((s_33556855).length <= i_33556895) || (s_33556855[i_33556895] < 128))) {
                  break Label3;
                  }
                  
                  c_33556897 = s_33556855[i_33556895];
                }
            };
++excHandler;
            try {
            res_33556894[j_33556896] = decodeURIComponent(helper_33556910.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556894[j_33556896] = helper_33556910.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556896 += 1;
        }
    };
    if (res_33556894.length < j_33556896) { for (var i = res_33556894.length ; i < j_33556896 ; ++i) res_33556894.push(null); }
               else { res_33556894.length = j_33556896; };
    result_33556856 = res_33556894.join("");

  return result_33556856;

}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function newSeq_33556873(len_33556875) {
  var result_33556876 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 597;
    result_33556876 = new Array(len_33556875); for (var i = 0 ; i < len_33556875 ; ++i) { result_33556876[i] = null; }  framePtr = F.prev;

  return result_33556876;

}

function HEX3Aanonymous_654311427() {
  var F = {procname: "jscore_examples_3.:anonymous", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
  framePtr = F;
    F.line = 146;
    rawEcho([77,105,99,114,111,116,97,115,107]);
  framePtr = F.prev;

  
}
var F = {procname: "module jscore_examples_3", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
framePtr = F;
F.line = 146;
queueMicrotask(HEX3Aanonymous_654311427);
framePtr = F.prev;
var F = {procname: "module jscore_examples_3", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore_group1_examples", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jscore_group1_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore_group1_examples", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jscore_group1_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
