# autogenerated by docgen
# source: /home/runner/work/nim-lang/nim-lang/lib/js/jscore.nim
# rdoccmd: 
import "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jscore_examples_1.nim"
import "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jscore_examples_2.nim"
