/* Generated by the Nim Compiler v1.9.3 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33555181 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI989855748 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI989855747 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI671088651 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI671088647 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI671088648 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI671088646 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI671088645 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI671088644 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555824 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555178 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555176 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
var NNI33555176 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555176.node = NNI33555176;
NTI33555178.base = NTI33555175;
NTI33555179.base = NTI33555175;
var NNI33555175 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555178, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555179, name: "up", sons: null}]};
NTI33555175.node = NNI33555175;
var NNI33555171 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555171.node = NNI33555171;
NTI33555175.base = NTI33555171;
NTI33555176.base = NTI33555175;
NTI134217745.base = NTI33555176;
var NNI33555824 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555824.node = NNI33555824;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
NTI134217741.base = NTI33555176;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555176;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555176;
var NNI671088644 = {kind: 2, offset: 0, typ: null, name: null, len: 3, sons: {"0": {kind: 1, offset: 0, typ: NTI671088644, name: "cors", len: 0, sons: null}, 
"1": {kind: 1, offset: 1, typ: NTI671088644, name: "no-cors", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI671088644, name: "same-origin", len: 0, sons: null}}};
NTI671088644.node = NNI671088644;
var NNI671088645 = {kind: 2, offset: 0, typ: null, name: null, len: 3, sons: {"0": {kind: 1, offset: 0, typ: NTI671088645, name: "include", len: 0, sons: null}, 
"1": {kind: 1, offset: 1, typ: NTI671088645, name: "same-origin", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI671088645, name: "omit", len: 0, sons: null}}};
NTI671088645.node = NNI671088645;
var NNI671088646 = {kind: 2, offset: 0, typ: null, name: null, len: 5, sons: {"0": {kind: 1, offset: 0, typ: NTI671088646, name: "default", len: 0, sons: null}, 
"1": {kind: 1, offset: 1, typ: NTI671088646, name: "no-store", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI671088646, name: "reload", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI671088646, name: "no-cache", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI671088646, name: "force-cache", len: 0, sons: null}}};
NTI671088646.node = NNI671088646;
var NNI671088648 = {kind: 2, offset: 0, typ: null, name: null, len: 5, sons: {"0": {kind: 1, offset: 0, typ: NTI671088648, name: "no-referrer", len: 0, sons: null}, 
"1": {kind: 1, offset: 1, typ: NTI671088648, name: "no-referrer-when-downgrade", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI671088648, name: "origin", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI671088648, name: "origin-when-cross-origin", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI671088648, name: "unsafe-url", len: 0, sons: null}}};
NTI671088648.node = NNI671088648;
var NNI671088647 = {kind: 2, offset: 0, typ: null, name: null, len: 3, sons: {"0": {kind: 1, offset: 0, typ: NTI671088647, name: "follow", len: 0, sons: null}, 
"1": {kind: 1, offset: 1, typ: NTI671088647, name: "error", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI671088647, name: "manual", len: 0, sons: null}}};
NTI671088647.node = NNI671088647;
var NNI989855748 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI989855748.node = NNI989855748;
var NNI33555181 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555181.node = NNI33555181;
NTI33555181.base = NTI33555171;
NTI989855748.base = NTI33555181;
NTI989855747.base = NTI989855748;
var NNI671088651 = {kind: 2, len: 11, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "keepalive", len: 0, typ: NTI33554466, name: "keepalive", sons: null}, 
{kind: 1, offset: "method", len: 0, typ: NTI33554450, name: "metod", sons: null}, 
{kind: 1, offset: "body", len: 0, typ: NTI33554450, name: "body", sons: null}, 
{kind: 1, offset: "integrity", len: 0, typ: NTI33554450, name: "integrity", sons: null}, 
{kind: 1, offset: "referrer", len: 0, typ: NTI33554450, name: "referrer", sons: null}, 
{kind: 1, offset: "mode", len: 0, typ: NTI33554450, name: "mode", sons: null}, 
{kind: 1, offset: "credentials", len: 0, typ: NTI33554450, name: "credentials", sons: null}, 
{kind: 1, offset: "cache", len: 0, typ: NTI33554450, name: "cache", sons: null}, 
{kind: 1, offset: "redirect", len: 0, typ: NTI33554450, name: "redirect", sons: null}, 
{kind: 1, offset: "referrerPolicy", len: 0, typ: NTI33554450, name: "referrerPolicy", sons: null}, 
{kind: 1, offset: "headers", len: 0, typ: NTI989855747, name: "headers", sons: null}]};
NTI671088651.node = NNI671088651;
NTI671088651.base = NTI33555181;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557210, src_33557211, ti_33557212) {
  var result_33557221 = null;

    switch (ti_33557212.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557201(ti_33557212))) {
      result_33557221 = src_33557211;
      }
      else {
        result_33557221 = [src_33557211[0], src_33557211[1]];
      }
      
      break;
    case 19:
            if (dest_33557210 === null || dest_33557210 === undefined) {
        dest_33557210 = {};
      }
      else {
        for (var key in dest_33557210) { delete dest_33557210[key]; }
      }
      for (var key in src_33557211) { dest_33557210[key] = src_33557211[key]; }
      result_33557221 = dest_33557210;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557212.base == null))) {
      result_33557221 = nimCopy(dest_33557210, src_33557211, ti_33557212.base);
      }
      else {
      if ((ti_33557212.kind == 17)) {
      result_33557221 = (dest_33557210 === null || dest_33557210 === undefined) ? {m_type: ti_33557212} : dest_33557210;
      }
      else {
        result_33557221 = (dest_33557210 === null || dest_33557210 === undefined) ? {} : dest_33557210;
      }
      }
      nimCopyAux(result_33557221, src_33557211, ti_33557212.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557211)) { 
        if(dest_33557210 === null || dest_33557210 === undefined || dest_33557210.length != src_33557211.length) {
          dest_33557210 = new src_33557211.constructor(src_33557211);
        } else {
          dest_33557210.set(src_33557211, 0);
        }
        result_33557221 = dest_33557210;
      } else {
        if (src_33557211 === null) {
          result_33557221 = null;
        }
        else {
          if (dest_33557210 === null || dest_33557210 === undefined || dest_33557210.length != src_33557211.length) {
            dest_33557210 = new Array(src_33557211.length);
          }
          result_33557221 = dest_33557210;
          for (var i = 0; i < src_33557211.length; ++i) {
            result_33557221[i] = nimCopy(result_33557221[i], src_33557211[i], ti_33557212.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557211 === null) {
        result_33557221 = null;
      }
      else {
        if (dest_33557210 === null || dest_33557210 === undefined || dest_33557210.length != src_33557211.length) {
          dest_33557210 = new Array(src_33557211.length);
        }
        result_33557221 = dest_33557210;
        for (var i = 0; i < src_33557211.length; ++i) {
          result_33557221[i] = nimCopy(result_33557221[i], src_33557211[i], ti_33557212.base);
        }
      }
    
      break;
    case 28:
            if (src_33557211 !== null) {
        result_33557221 = src_33557211.slice(0);
      }
    
      break;
    default: 
      result_33557221 = src_33557211;
      break;
    }

  return result_33557221;

}

function arrayConstr(len_33557253, value_33557254, typ_33557255) {
        var result = new Array(len_33557253);
    for (var i = 0; i < len_33557253; ++i) result[i] = nimCopy(null, value_33557254, typ_33557255);
    return result;
  

  
}

function mnewString(len_33556951) {
        return new Array(len_33556951);
  

  
}

function addInt(a_33556998, b_33556999) {
        var result = a_33556998 + b_33556999;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557263, a_33557264, b_33557265) {
  var result_33557266 = 0;

  BeforeRet: {
    if (((a_33557264 <= i_33557263) && (i_33557263 <= b_33557265))) {
    result_33557266 = i_33557263;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557266;

}

function chckIndx(i_33557258, a_33557259, b_33557260) {
  var result_33557261 = 0;

  BeforeRet: {
    if (((a_33557259 <= i_33557258) && (i_33557258 <= b_33557260))) {
    result_33557261 = i_33557258;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557258, a_33557259, b_33557260);
    }
    
  };

  return result_33557261;

}

function cstrToNimstr(c_33556852) {
      var ln = c_33556852.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556852.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556852.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function toJSStr(s_33556855) {
  var result_33556856 = null;

    var res_33556894 = newSeq_33556873((s_33556855).length);
    var i_33556895 = 0;
    var j_33556896 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556895 < (s_33556855).length)) break Label2;
          var c_33556897 = s_33556855[i_33556895];
          if ((c_33556897 < 128)) {
          res_33556894[j_33556896] = String.fromCharCode(c_33556897);
          i_33556895 += 1;
          }
          else {
            var helper_33556910 = newSeq_33556873(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556911 = c_33556897.toString(16);
                  if ((((code_33556911) == null ? 0 : (code_33556911).length) == 1)) {
                  helper_33556910.push("%0");;
                  }
                  else {
                  helper_33556910.push("%");;
                  }
                  
                  helper_33556910.push(code_33556911);;
                  i_33556895 += 1;
                  if ((((s_33556855).length <= i_33556895) || (s_33556855[i_33556895] < 128))) {
                  break Label3;
                  }
                  
                  c_33556897 = s_33556855[i_33556895];
                }
            };
++excHandler;
            try {
            res_33556894[j_33556896] = decodeURIComponent(helper_33556910.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556894[j_33556896] = helper_33556910.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556896 += 1;
        }
    };
    if (res_33556894.length < j_33556896) { for (var i = res_33556894.length ; i < j_33556896 ; ++i) res_33556894.push(null); }
               else { res_33556894.length = j_33556896; };
    result_33556856 = res_33556894.join("");

  return result_33556856;

}

function raiseException(e_33556643, ename_33556644) {
    e_33556643.name = ename_33556644;
    if ((excHandler == 0)) {
    unhandledException(e_33556643);
    }
    
    e_33556643.trace = nimCopy(null, rawWriteStackTrace_33556600(), NTI33554449);
    throw e_33556643;

  
}

function makeNimstrLit(c_33556849) {
      var result = [];
  for (var i = 0; i < c_33556849.length; ++i) {
    result[i] = c_33556849.charCodeAt(i);
  }
  return result;
  

  
}
var ConstSet2 = setConstr(0, 1);

function reprEnum(e_33557506, typ_33557507) {
  var result_33557508 = [];

  var F = {procname: "system.reprEnum", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/system/reprjs.nim", line: 0};
  framePtr = F;
    F.line = 30;
    var tmp_33557509 = false;
    F.line = 31;
    var item_33557510 = typ_33557507.node.sons[e_33557506];
    F.line = 32;
    tmp_33557509 = item_33557510 !== undefined
    if (tmp_33557509) {
    F.line = 34;
    result_33557508 = nimCopy(null, makeNimstrLit(item_33557510.name), NTI33554449);
    }
    else {
      F.line = 36;
      result_33557508 = nimCopy(null, (HEX24_369098760(e_33557506) || []).concat([32,40,105,110,118,97,108,105,100,32,100,97,116,97,33,41] || []), NTI33554449);
    }
    
  framePtr = F.prev;

  return result_33557508;

}
var F = {procname: "module macros", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/hashes.nim", line: 0};
framePtr = F;
F.line = 218;
var objectID_754974891 = [0];
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/hashes.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/js/jsffi.nim", line: 0};
framePtr = F;
F.line = 45;
F.line = 46;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/js/jsffi.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/js/asyncjs.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/js/asyncjs.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsheaders", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/jsheaders.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsheaders", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/jsheaders.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module httpcore", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/httpcore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module httpcore", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/httpcore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsfetch", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/jsfetch.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsfetch", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/jsfetch.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module underscored_calls", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/private/underscored_calls.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module underscored_calls", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/private/underscored_calls.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sugar", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/sugar.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sugar", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/pure/sugar.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function isFatPointer_33557201(ti_33557202) {
  var result_33557203 = false;

  BeforeRet: {
    result_33557203 = !((ConstSet1[ti_33557202.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557203;

}

function nimCopyAux(dest_33557214, src_33557215, n_33557216) {
    switch (n_33557216.kind) {
    case 0:
      break;
    case 1:
            dest_33557214[n_33557216.offset] = nimCopy(dest_33557214[n_33557216.offset], src_33557215[n_33557216.offset], n_33557216.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557216.sons.length; i++) {
      nimCopyAux(dest_33557214, src_33557215, n_33557216.sons[i]);
    }
    
      break;
    case 3:
            dest_33557214[n_33557216.offset] = nimCopy(dest_33557214[n_33557216.offset], src_33557215[n_33557216.offset], n_33557216.typ);
      for (var i = 0; i < n_33557216.sons.length; ++i) {
        nimCopyAux(dest_33557214, src_33557215, n_33557216.sons[i][1]);
      }
    
      break;
    }

  
}

function add_33556387(x_33556388, x_33556388_Idx, y_33556389) {
          if (x_33556388[x_33556388_Idx] === null) { x_33556388[x_33556388_Idx] = []; }
      var off = x_33556388[x_33556388_Idx].length;
      x_33556388[x_33556388_Idx].length += y_33556389.length;
      for (var i = 0; i < y_33556389.length; ++i) {
        x_33556388[x_33556388_Idx][off+i] = y_33556389.charCodeAt(i);
      }
    

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33556996) {
        if (a_33556996 > 2147483647 || a_33556996 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function raiseIndexError(i_33556778, a_33556779, b_33556780) {
    var Temporary1;

    if ((b_33556780 < a_33556779)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24_369098760(i_33556778) || [],[32,110,111,116,32,105,110,32] || [],HEX24_369098760(a_33556779) || [],[32,46,46,32] || [],HEX24_369098760(b_33556780) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function addChars_301990072(result_301990074, result_301990074_Idx, x_301990075, start_301990076, n_301990077) {
    var Temporary1;

  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 43;
    var old_301990078 = (result_301990074[result_301990074_Idx]).length;
    F.line = 44;
    if (result_301990074[result_301990074_Idx].length < (Temporary1 = chckRange(addInt(old_301990078, n_301990077), 0, 2147483647), Temporary1)) { for (var i = result_301990074[result_301990074_Idx].length; i < Temporary1; ++i) result_301990074[result_301990074_Idx].push(0); }
         else {result_301990074[result_301990074_Idx].length = Temporary1; };
    Label2: {
      F.line = 46;
      var iHEX60gensym4_301990092 = 0;
      F.line = 119;
      var i_654311861 = 0;
      Label3: {
        F.line = 120;
          Label4: while (true) {
          if (!(i_654311861 < n_301990077)) break Label4;
            F.line = 49;
            iHEX60gensym4_301990092 = i_654311861;
            F.line = 49;
            result_301990074[result_301990074_Idx][chckIndx(addInt(old_301990078, iHEX60gensym4_301990092), 0, (result_301990074[result_301990074_Idx]).length - 1)] = x_301990075.charCodeAt(chckIndx(addInt(start_301990076, iHEX60gensym4_301990092), 0, (x_301990075).length - 1));
            F.line = 122;
            i_654311861 = addInt(i_654311861, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars_301990068(result_301990070, result_301990070_Idx, x_301990071) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 55;
    addChars_301990072(result_301990070, result_301990070_Idx, x_301990071, 0, ((x_301990071) == null ? 0 : (x_301990071).length));
  framePtr = F.prev;

  
}

function addInt_301990093(result_301990094, result_301990094_Idx, x_301990095) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 111;
    addChars_301990068(result_301990094, result_301990094_Idx, ((x_301990095) + ""));
  framePtr = F.prev;

  
}

function addInt_301990111(result_301990112, result_301990112_Idx, x_301990113) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 115;
    addInt_301990093(result_301990112, result_301990112_Idx, BigInt(x_301990113));
  framePtr = F.prev;

  
}

function HEX24_369098760(x_369098761) {
  var result_369098762 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 18;
    addInt_301990111(result_369098762, 0, x_369098761);
  framePtr = F.prev;

  return result_369098762[0];

}

function auxWriteStackTrace_33556513(f_33556514) {
  var result_33556515 = [[]];

    var it_33556523 = f_33556514;
    var i_33556524 = 0;
    var total_33556525 = 0;
    var tempFrames_33556526 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555824);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556523 == null)) && (i_33556524 <= 63))) break Label2;
          tempFrames_33556526[i_33556524].Field0 = it_33556523.procname;
          tempFrames_33556526[i_33556524].Field1 = it_33556523.line;
          tempFrames_33556526[i_33556524].Field2 = it_33556523.filename;
          i_33556524 += 1;
          total_33556525 += 1;
          it_33556523 = it_33556523.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556523 == null))) break Label4;
          total_33556525 += 1;
          it_33556523 = it_33556523.prev;
        }
    };
    result_33556515[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556525 == i_33556524))) {
    result_33556515[0].push.apply(result_33556515[0], [40]);;
    result_33556515[0].push.apply(result_33556515[0], HEX24_369098760((total_33556525 - i_33556524)));;
    result_33556515[0].push.apply(result_33556515[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556559 = 0;
      var colontmp__654311853 = 0;
      colontmp__654311853 = (i_33556524 - 1);
      var res_654311855 = colontmp__654311853;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_654311855)) break Label7;
            j_33556559 = res_654311855;
            result_33556515[0].push.apply(result_33556515[0], cstrToNimstr(tempFrames_33556526[j_33556559].Field2));;
            if ((0 < tempFrames_33556526[j_33556559].Field1)) {
            result_33556515[0].push.apply(result_33556515[0], [40]);;
            addInt_301990111(result_33556515, 0, tempFrames_33556526[j_33556559].Field1);
            if (false) {
            result_33556515[0].push.apply(result_33556515[0], [44,32]);;
            addInt_301990111(result_33556515, 0, 0);
            }
            
            result_33556515[0].push.apply(result_33556515[0], [41]);;
            }
            
            result_33556515[0].push.apply(result_33556515[0], [32,97,116,32]);;
            add_33556387(result_33556515, 0, tempFrames_33556526[j_33556559].Field0);
            result_33556515[0].push.apply(result_33556515[0], [10]);;
            res_654311855 -= 1;
          }
      };
    };

  return result_33556515[0];

}

function rawWriteStackTrace_33556600() {
  var result_33556601 = [];

    if (!((framePtr == null))) {
    result_33556601 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10] || []).concat(auxWriteStackTrace_33556513(framePtr) || []), NTI33554449);
    }
    else {
      result_33556601 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556601;

}

function newSeq_33556873(len_33556875) {
  var result_33556876 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 597;
    result_33556876 = new Array(len_33556875); for (var i = 0 ; i < len_33556875 ; ++i) { result_33556876[i] = null; }  framePtr = F.prev;

  return result_33556876;

}

function unhandledException(e_33556639) {
    var buf_33556640 = [[]];
    if (!(((e_33556639.message).length == 0))) {
    buf_33556640[0].push.apply(buf_33556640[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556640[0].push.apply(buf_33556640[0], e_33556639.message);;
    }
    else {
    buf_33556640[0].push.apply(buf_33556640[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556640[0].push.apply(buf_33556640[0], [32,91]);;
    add_33556387(buf_33556640, 0, e_33556639.name);
    buf_33556640[0].push.apply(buf_33556640[0], [93,10]);;
    buf_33556640[0].push.apply(buf_33556640[0], rawWriteStackTrace_33556600());;
    var cbuf_33556641 = toJSStr(buf_33556640[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556641);
  }
  else {
    throw cbuf_33556641;
  }
  

  
}

function sysFatal_268435498(message_268435501) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 53;
    raiseException({message: nimCopy(null, message_268435501, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert_268435496(msg_268435497) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 36;
    sysFatal_268435498(msg_268435497);
  framePtr = F.prev;

  
}

function failedAssertImpl_268435532(msg_268435533) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 41;
    raiseAssert_268435496(msg_268435533);
  framePtr = F.prev;

  
}

function newfetchOptions_671088755(metod_671088756, body_671088757, mode_671088758, credentials_671088759, cache_671088760, referrerPolicy_671088761, keepalive_671088762, redirect_671088763, referrer_671088764, integrity_671088765, headers_671088766) {
    var Temporary1;
    var Temporary2;

  var result_671088767 = null;

  var F = {procname: "jsfetch.newfetchOptions", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/std/jsfetch.nim", line: 0};
  framePtr = F;
    F.line = 93;
    if (!((ConstSet2[metod_671088756] != undefined))) {
    Temporary1 = body_671088757;
    }
    else {
    Temporary1 = null;
    }
    
    F.line = 97;
    switch (metod_671088756) {
    case 0:
      Temporary2 = "HEAD";
      break;
    case 1:
      Temporary2 = "GET";
      break;
    case 2:
      Temporary2 = "POST";
      break;
    case 3:
      Temporary2 = "PUT";
      break;
    case 4:
      Temporary2 = "DELETE";
      break;
    case 8:
      Temporary2 = "PATCH";
      break;
    default: 
      Temporary2 = "GET";
      break;
    }
    result_671088767 = {body: Temporary1, mode: toJSStr(reprEnum(mode_671088758, NTI671088644)), credentials: toJSStr(reprEnum(credentials_671088759, NTI671088645)), cache: toJSStr(reprEnum(cache_671088760, NTI671088646)), referrerPolicy: toJSStr(reprEnum(referrerPolicy_671088761, NTI671088648)), keepalive: keepalive_671088762, redirect: toJSStr(reprEnum(redirect_671088763, NTI671088647)), referrer: referrer_671088764, integrity: integrity_671088765, headers: headers_671088766, method: Temporary2, m_type: NTI671088651};
  framePtr = F.prev;

  return result_671088767;

}
async function doFetch_654311594() {
  var result_654311596 = null;

  var F = {procname: "jsfetch_examples_1.doFetch", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim", line: 0};
  framePtr = F;
    F.line = 119;
    result_654311596 = fetch("https://httpbin.org/get");
  framePtr = F.prev;

  return result_654311596;

}
async function example_654311623() {
  var result_654311625 = null;

  var F = {procname: "jsfetch_examples_1.example", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 119;
    var response_654311635 = (await doFetch_654311594());
    if (!(response_654311635.ok)) {
    F.line = 119;
    failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(77, 9) `response.ok` "));
    }
    
    if (!((response_654311635.status == 200))) {
    F.line = 119;
    failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(78, 9) `response.status == 200.cint` "));
    }
    
    if (false) {
    F.line = 119;
    failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(79, 9) `response.headers is Headers` "));
    }
    
    if (false) {
    F.line = 119;
    failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(80, 9) `response.body is cstring` "));
    }
    
    F.line = 119;
    result_654311625 = undefined;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_654311625;

}

function catch_654311798(future_654311800, onReject_654311801) {
  var result_654311802 = null;

  var F = {procname: "catch.catch", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/js/asyncjs.nim", line: 0};
  framePtr = F;
    F.line = 267;
    result_654311802 = future_654311800.catch(onReject_654311801)
  framePtr = F.prev;

  return result_654311802;

}

function then_654311772(future_654311775, onSuccess_654311776, onReject_654311777) {
  var result_654311778 = null;

  var F = {procname: "then.then", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/js/asyncjs.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 243;
    var ret_654311793 = null;
    F.line = 244;
    ret_654311793 = future_654311775.then(onSuccess_654311776, onReject_654311777)
    F.line = 245;
    result_654311778 = ret_654311793;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_654311778;

}

function then_654311731(future_654311734, onSuccess_654311735, onReject_654311736) {
  var result_654311737 = null;

  var F = {procname: "then.then", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/lib/js/asyncjs.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 243;
    var ret_654311767 = null;
    F.line = 244;
    ret_654311767 = future_654311734.then(onSuccess_654311735, onReject_654311736)
    F.line = 245;
    result_654311737 = ret_654311767;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_654311737;

}
async function example2_654311685() {
    
function HEX3Aanonymous_654311715(response_654311716) {
      var result_654311717 = null;

      var F = {procname: "example2.:anonymous", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim", line: 0};
      framePtr = F;
        F.line = 87;
        result_654311717 = response_654311716.json();
      framePtr = F.prev;

      return result_654311717;

    }
    
function HEX3Aanonymous_654311769(json_654311770) {
      var F = {procname: "example2.:anonymous", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim", line: 0};
      framePtr = F;
        F.line = 88;
        console.log(json_654311770);
      framePtr = F.prev;

      
    }
    
function HEX3Aanonymous_654311795(err_654311796) {
      var F = {procname: "example2.:anonymous", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim", line: 0};
      framePtr = F;
        F.line = 119;
        console.log("Request Failed", err_654311796);
      framePtr = F.prev;

      
    }

  var result_654311687 = null;

  var F = {procname: "jsfetch_examples_1.example2", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 119;
    (await catch_654311798(then_654311772(then_654311731(fetch("https://api.github.com/users/torvalds"), HEX3Aanonymous_654311715, null), HEX3Aanonymous_654311769, null), HEX3Aanonymous_654311795));
    F.line = 119;
    result_654311687 = undefined;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_654311687;

}
var F = {procname: "module jsfetch_examples_1", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim", line: 0};
framePtr = F;
Label1: {
  F.line = 119;
  var options0_654311434 = {method: "POST", body: "{\"key\": \"value\"}", mode: "no-cors", credentials: "omit", cache: "no-cache", referrerPolicy: "no-referrer", keepalive: false, redirect: "follow", referrer: "client", integrity: "", headers: new Headers()};
  if (!((options0_654311434.keepalive == false))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(28, 5) `options0.keepalive == false` "));
  }
  
  if (!((options0_654311434.method == "POST"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(29, 5) `options0.metod == \"POST\".cstring` "));
  }
  
  if (!((options0_654311434.body == "{\"key\": \"value\"}"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(30, 5) `options0.body == \"\"\"{\"key\": \"value\"}\"\"\".cstring` "));
  }
  
  if (!((options0_654311434.mode == "no-cors"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(31, 5) `options0.mode == \"no-cors\".cstring` "));
  }
  
  if (!((options0_654311434.credentials == "omit"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(32, 5) `options0.credentials == \"omit\".cstring` "));
  }
  
  if (!((options0_654311434.cache == "no-cache"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(33, 5) `options0.cache == \"no-cache\".cstring` "));
  }
  
  if (!((options0_654311434.referrerPolicy == "no-referrer"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(34, 5) `options0.referrerPolicy == \"no-referrer\".cstring` "));
  }
  
  if (!((options0_654311434.redirect == "follow"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(35, 5) `options0.redirect == \"follow\".cstring` "));
  }
  
  if (!((options0_654311434.referrer == "client"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(36, 5) `options0.referrer == \"client\".cstring` "));
  }
  
  if (!((options0_654311434.integrity == ""))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(37, 5) `options0.integrity == \"\".cstring` "));
  }
  
  if (!((Array.from(options0_654311434.headers.entries()).length == 0))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(38, 5) `options0.headers.len == 0` "));
  }
  
};
Label2: {
  F.line = 119;
  var options1_654311490 = newfetchOptions_671088755(2, "{\"key\": \"value\"}", 1, 2, 3, 0, false, 0, "client", "", new Headers());
  if (!((options1_654311490.keepalive == false))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(54, 5) `options1.keepalive == false` "));
  }
  
  if (!((options1_654311490.method == "POST"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(55, 5) `options1.metod == $HttpPost` "));
  }
  
  if (!((options1_654311490.body == "{\"key\": \"value\"}"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(56, 5) `options1.body == \"\"\"{\"key\": \"value\"}\"\"\".cstring` "));
  }
  
  if (!((options1_654311490.mode == "no-cors"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(57, 5) `options1.mode == $fmNoCors` "));
  }
  
  if (!((options1_654311490.credentials == "omit"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(58, 5) `options1.credentials == $fcOmit` "));
  }
  
  if (!((options1_654311490.cache == "no-cache"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(59, 5) `options1.cache == $fchNoCache` "));
  }
  
  if (!((options1_654311490.referrerPolicy == "no-referrer"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(60, 5) `options1.referrerPolicy == $frpNoReferrer` "));
  }
  
  if (!((options1_654311490.redirect == "follow"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(61, 5) `options1.redirect == $frFollow` "));
  }
  
  if (!((options1_654311490.referrer == "client"))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(62, 5) `options1.referrer == \"client\".cstring` "));
  }
  
  if (!((options1_654311490.integrity == ""))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(63, 5) `options1.integrity == \"\".cstring` "));
  }
  
  if (!((Array.from(options1_654311490.headers.entries()).length == 0))) {
  F.line = 119;
  failedAssertImpl_268435532(makeNimstrLit("/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim(64, 5) `options1.headers.len == 0` "));
  }
  
};
Label3: {
  F.line = 119;
  var response_654311567 = (new Response("-. .. --"));
  F.line = 119;
  var request_654311568 = (new Request("http://nim-lang.org"));
};
if (true) {
Label4: {
  F.line = 119;
  var _ = example_654311623();
};
Label5: {
  F.line = 119;
  var _ = example2_654311685();
};
}

framePtr = F.prev;
var F = {procname: "module jsfetch_examples_1", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsfetch_group0_examples", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsfetch_group0_examples", prev: framePtr, filename: "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
