# autogenerated by docgen
# source: /home/runner/work/nim-lang/nim-lang/lib/std/jsfetch.nim
# rdoccmd: -r:off
import "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim"
