#[
autogenerated by docgen
loc: /home/runner/work/nim-lang/nim-lang/lib/std/jsformdata.nim(61, 17)
rdoccmd: -r:off
]#
import std/assertions
import "/home/runner/work/nim-lang/nim-lang/lib/std/jsformdata.nim"
{.line: ("/home/runner/work/nim-lang/nim-lang/lib/std/jsformdata.nim", 61, 17).}:
  let data: FormData = newFormData()
  data["key0"] = "value0".cstring
  data.add("key1".cstring, "value1".cstring)
  data.delete("key1")
  assert data.hasKey("key0")
  assert data["key0"] == "value0".cstring
  data.clear()
  assert data.len == 0

