# autogenerated by docgen
# source: /home/runner/work/nim-lang/nim-lang/lib/std/jsformdata.nim
# rdoccmd: -r:off
import "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsformdata_examples_1.nim"
