# autogenerated by docgen
# source: /home/runner/work/nim-lang/nim-lang/lib/std/jsheaders.nim
# rdoccmd: -r:off
import "/home/runner/work/nim-lang/nim-lang/doc/html/nimcache/runnableExamples/jsheaders_examples_1.nim"
